
name: Comunicador de la legion

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "Nombre del villano que envia mensaje?"
        required: true
        type: choice
        options:
          - Joker
          - Thanos
          - Magneto
          - Loki
          - Venom
      prioridad:
        description: "Nivel de prioridad de la misión"
        required: true
        type: choice
        options:
          - baja
          - media
          - alta
          - critica
      mensaje:
        description: "Mensaje o directiva para la legión"
        required: false
        type: string
        default: "La misión fue un éxito, nos vemos en el inframundo"
      cow-character:
        description: "Personaje que enviará el mensaje"
        required: false
        type: choice
        default: "eyes"
        options:
          - tux
          - ghostbusters
          - dragon
          - stegosaurus
          - daemon
          - cheese
          - hellokitty
          - ren
          - bong
          - beavis

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: instalar emisor de la legion
        run: |
          echo "instalar emisor de la legion"
          sudo apt-get update
          sudo apt-get install -y cowsay

      - name: Enviando mensaje a la legión
        run: |
          echo "Desde la base oculta de la legión del mal"
          echo "El villano ${{inputs.villano}} nos informa:"
          echo ""
          echo "Prioridad: ${{inputs.prioridad}}"
          echo ""
          echo "Mensaje:"
          cowsay -f ${{inputs.cow-character}} "${{inputs.mensaje}}"
          echo ""
          echo "---- ${{inputs.villano}}"
      
